import 'package:Read_Lead/db/topic.dart';

final List<Topic> PRINCE2Topics = [
  Topic(
    name: "1. Introduction",
    startPage: 20,
    subTopics: [
      Topic(name: "1.1 Introduction", startPage: 21),
      Topic(name: "1.2 Structure of the official book", startPage: 22),
      Topic(name: "1.3 What is a project?", startPage: 24),
      Topic(name: "1.4 What is project management?", startPage: 25),
      Topic(name: "1.5 The project context", startPage: 26),
      Topic(name: "1.6 Features and benefits of PRINCE2", startPage: 31),
      Topic(name: "1.7 Example scenarios", startPage: 31),
    ],
  ),
  Topic(
    name: "2. Principles",
    startPage: 38,
    subTopics: [
      Topic(name: "2.1 Ensure continued business justification", startPage: 40),
      Topic(name: "2.2 Learn from experience", startPage: 41),
      Topic(name: "2.3 Define roles, responsibilities, and relationships", startPage: 43),
      Topic(name: "2.4 Manage by exception", startPage: 44),
      Topic(name: "2.5 Manage by stages", startPage: 46),
      Topic(name: "2.6 Focus on products", startPage: 47),
      Topic(name: "2.7 Tailor to suit the project", startPage: 48),
    ],
  ),
  Topic(
    name: "3. People",
    startPage: 50,
    subTopics: [
      Topic(name: "3.1 Context", startPage: 51),
      Topic(name: "3.2 Leading successful change", startPage: 53),
      Topic(name: "3.3 Leading successful teams", startPage: 58),
      Topic(name: "3.4 Communication", startPage: 61),
      Topic(name: "3.5 People are central to the method", startPage: 64),
    ],
  ),
  Topic(
    name: "4. Introduction to PRINCE2 Practices",
    startPage: 68,
    subTopics: [
      Topic(name: "4.1 The PRINCE2 practices", startPage: 69),
      Topic(name: "4.2 Applying the practices", startPage: 70),
      Topic(name: "4.3 Management products", startPage: 71),
      Topic(name: "4.4 Format of the practice chapters", startPage: 73),
    ],
  ),
  Topic(
    name: "5. Business Case",
    startPage: 74,
    subTopics: [
      Topic(name: "5.1 Purpose", startPage: 75),
      Topic(name: "5.2 Guidance for effective business case management", startPage: 77),
      Topic(name: "5.3 Techniques", startPage: 79),
      Topic(name: "5.4 Applying the practice", startPage: 84),
      Topic(name: "5.5 Management products to support the practice", startPage: 87),
      Topic(name: "5.6 Focus of key roles for the practice", startPage: 90),
      Topic(name: "5.7 Key relationships with principles", startPage: 91),
    ],
  ),
  Topic(
    name: "6. Organizing",
    startPage: 92,
    subTopics: [
      Topic(name: "6.1 Purpose", startPage: 93),
      Topic(name: "6.2 Guidance for effective organizing", startPage: 93),
      Topic(name: "6.3 Techniques", startPage: 102),
      Topic(name: "6.4 Applying the practice", startPage: 107),
      Topic(name: "6.5 Management products to support the practice", startPage: 111),
      Topic(name: "6.6 Focus of key roles for the practice", startPage: 112),
      Topic(name: "6.7 Key relationships with principles", startPage: 114),
    ],
  ),
  Topic(
    name: "7. Plans",
    startPage: 116,
    subTopics: [
      Topic(name: "7.1 Purpose", startPage: 117),
      Topic(name: "7.2 Guidance for effective planning", startPage: 118),
      Topic(name: "7.3 Techniques", startPage: 126),
      Topic(name: "7.4 Applying the practice", startPage: 137),
      Topic(name: "7.5 Management products to support the practice", startPage: 140),
      Topic(name: "7.6 Focus of key roles for the practice", startPage: 143),
      Topic(name: "7.7 Key relationships with principles", startPage: 144),
    ],
  ),
  Topic(
    name: "8. Quality",
    startPage: 146,
    subTopics: [
      Topic(name: "8.1 Purpose", startPage: 147),
      Topic(name: "8.2 Guidance for effective quality management", startPage: 149),
      Topic(name: "8.3 Techniques", startPage: 154),
      Topic(name: "8.4 Applying the practice", startPage: 159),
      Topic(name: "8.5 Management products to support the practice", startPage: 162),
      Topic(name: "8.6 Focus of key roles for the practice", startPage: 164),
      Topic(name: "8.7 Key relationships with principles", startPage: 165),
    ],
  ),
  Topic(
    name: "9. Risk",
    startPage: 166,
    subTopics: [
      Topic(name: "9.1 Purpose", startPage: 167),
      Topic(name: "9.2 Guidance for effective risk management", startPage: 168),
      Topic(name: "9.3 Techniques", startPage: 174),
      Topic(name: "9.4 Applying the practice", startPage: 179),
      Topic(name: "9.5 Management products to support the practice", startPage: 181),
      Topic(name: "9.6 Focus of key roles for the practice", startPage: 183),
      Topic(name: "9.7 Key relationships with principles", startPage: 184),
    ],
  ),
  Topic(
    name: "10. Issues",
    startPage: 186,
    subTopics: [
      Topic(name: "10.1 Purpose", startPage: 187),
      Topic(name: "10.2 Guidance for effective issue management", startPage: 188),
      Topic(name: "10.3 Techniques", startPage: 192),
      Topic(name: "10.4 Applying the practice", startPage: 196),
      Topic(name: "10.5 Management products to support the practice", startPage: 199),
      Topic(name: "10.6 Focus of key roles for the practice", startPage: 201),
      Topic(name: "10.7 Key relationships with principles", startPage: 202),
    ],
  ),
  Topic(
    name: "11. Progress",
    startPage: 204,
    subTopics: [
      Topic(name: "11.1 Purpose", startPage: 205),
      Topic(name: "11.2 Guidance for effective progress management", startPage: 206),
      Topic(name: "11.3 Techniques: progress management", startPage: 215),
      Topic(name: "11.4 Applying the progress practice", startPage: 221),
      Topic(name: "11.5 Management products to support the practice", startPage: 223),
      Topic(name: "11.6 Focus of key roles for the practice", startPage: 228),
      Topic(name: "11.7 Key relationships with principles", startPage: 230),
    ],
  ),
  Topic(
    name: "12. Introduction to PRINCE2 Processes",
    startPage: 232,
    subTopics: [
      Topic(name: "12.1 The PRINCE2 journey", startPage: 234),
      Topic(name: "12.2 The PRINCE2 process model", startPage: 235),
      Topic(name: "12.3 Format of the process chapters", startPage: 237),
    ],
  ),
  Topic(
    name: "13. Starting up a project",
    startPage: 238,
    subTopics: [
      Topic(name: "13.1 Purpose", startPage: 239),
      Topic(name: "13.2 Objectives", startPage: 239),
      Topic(name: "13.3 Context", startPage: 240),
      Topic(name: "13.4 Activities", startPage: 241),
      Topic(name: "13.5 Applying the process", startPage: 244),
      Topic(name: "13.6 Responsibilities", startPage: 245),
      Topic(name: "13.7 Application of the practices to this process", startPage: 246),
    ],
  ),
  Topic(
    name: "14. Directing a project",
    startPage: 248,
    subTopics: [
      Topic(name: "14.1 Purpose", startPage: 249),
      Topic(name: "14.2 Objectives", startPage: 249),
      Topic(name: "14.3 Context", startPage: 249),
      Topic(name: "14.4 Activities", startPage: 251),
      Topic(name: "14.5 Applying the process", startPage: 255),
      Topic(name: "14.6 Responsibilities", startPage: 255),
      Topic(name: "14.7 Application of the practices to this process", startPage: 256),
    ],
  ),
  Topic(
    name: "15. Initiating a project",
    startPage: 258,
    subTopics: [
      Topic(name: "15.1 Purpose", startPage: 259),
      Topic(name: "15.2 Objectives", startPage: 259),
      Topic(name: "15.3 Context", startPage: 260),
      Topic(name: "15.4 Activities", startPage: 261),
      Topic(name: "15.5 Applying the process", startPage: 266),
      Topic(name: "15.6 Responsibilities", startPage: 267),
      Topic(name: "15.7 Application of the practices to this process", startPage: 268),
    ],
  ),
  Topic(
    name: "16. Controlling a stage",
    startPage: 270,
    subTopics: [
      Topic(name: "16.1 Purpose", startPage: 271),
      Topic(name: "16.2 Objectives", startPage: 271),
      Topic(name: "16.3 Context", startPage: 272),
      Topic(name: "16.4 Activities", startPage: 273),
      Topic(name: "16.5 Applying the process", startPage: 278),
      Topic(name: "16.6 Responsibilities", startPage: 278),
      Topic(name: "16.7 Application of the practices to this process", startPage: 279),
    ],
  ),
  Topic(
    name: "17. Managing product delivery",
    startPage: 280,
    subTopics: [
      Topic(name: "17.1 Purpose", startPage: 281),
      Topic(name: "17.2 Objectives", startPage: 281),
      Topic(name: "17.3 Context", startPage: 282),
      Topic(name: "17.4 Activities", startPage: 283),
      Topic(name: "17.5 Applying the process", startPage: 285),
      Topic(name: "17.6 Responsibilities", startPage: 286),
      Topic(name: "17.7 Application of the practices to this process", startPage: 286),
    ],
  ),
  Topic(
    name: "18. Managing a stage boundary",
    startPage: 288,
    subTopics: [
      Topic(name: "18.1 Purpose", startPage: 289),
      Topic(name: "18.2 Objectives", startPage: 289),
      Topic(name: "18.3 Context", startPage: 290),
      Topic(name: "18.4 Activities", startPage: 291),
      Topic(name: "18.5 Applying the process", startPage: 294),
      Topic(name: "18.6 Responsibilities", startPage: 294),
      Topic(name: "18.7 Application of the practices to this process", startPage: 295),
    ],
  ),
  Topic(
    name: "19. Closing a project",
    startPage: 296,
    subTopics: [
      Topic(name: "19.1 Purpose", startPage: 297),
      Topic(name: "19.2 Objectives", startPage: 297),
      Topic(name: "19.3 Context", startPage: 298),
      Topic(name: "19.4 Activities", startPage: 299),
      Topic(name: "19.5 Applying the process", startPage: 302),
      Topic(name: "19.6 Responsibilities", startPage: 302),
      Topic(name: "19.7 Application of the practices to this process", startPage: 302),
    ],
  ),
  Topic(name: "Appendix A: Management Products", startPage: 304),
  Topic(name: "Appendix B: Role Descriptions", startPage: 326),
  Topic(name: "Glossary", startPage: 334),
  Topic(name: "Index", startPage: 352),
];
